//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tests.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press-release with Id = {0} hasn&apos;t an announcement.
        /// </summary>
        internal static string AnnouncementOfPressReleaseIsNotNull {
            get {
                return ResourceManager.GetString("AnnouncementOfPressReleaseIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of press-releases contains press-release with Id = {0} at incorrect date = &apos;{1}&apos;. Correct date is in period [{2} - {3}].
        /// </summary>
        internal static string CorrectFilteringByDateOfPressReleases {
            get {
                return ResourceManager.GetString("CorrectFilteringByDateOfPressReleases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press-release with Id = {0} has incorrect link to download PDF-file.
        /// </summary>
        internal static string CorrectLinkToDownloadPDFOfPressReleases {
            get {
                return ResourceManager.GetString("CorrectLinkToDownloadPDFOfPressReleases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press-release with Id = {0} has incorrect link to image of announcement.
        /// </summary>
        internal static string CorrectLinkToImageOfPressReleases {
            get {
                return ResourceManager.GetString("CorrectLinkToImageOfPressReleases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press-release with Id = {0} has incorrect link to link to watch PDF-file.
        /// </summary>
        internal static string CorrectLinkToWatchPDFOfPressReleases {
            get {
                return ResourceManager.GetString("CorrectLinkToWatchPDFOfPressReleases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of press-releases  = {0} after loading is great more than max value = {1}.
        /// </summary>
        internal static string CountOfPressReleasesAfterClickMore {
            get {
                return ResourceManager.GetString("CountOfPressReleasesAfterClickMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default count of press-releases = {0} doesn&apos;t match to value into config = {1}.
        /// </summary>
        internal static string DefaultCountOfPressReleases {
            get {
                return ResourceManager.GetString("DefaultCountOfPressReleases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title of press-release with Id = {0} into list doesn&apos;t match to title on page of press-release.
        /// </summary>
        internal static string MatchTitleOfPressReleasesOnListAndPage {
            get {
                return ResourceManager.GetString("MatchTitleOfPressReleasesOnListAndPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WDriver opens page by URL = &apos;{0}&apos;..
        /// </summary>
        internal static string OpenPage {
            get {
                return ResourceManager.GetString("OpenPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test failed because of error is &apos;{0}&apos;.
        /// </summary>
        internal static string ResultError {
            get {
                return ResourceManager.GetString("ResultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging for testing is started..
        /// </summary>
        internal static string StartLog {
            get {
                return ResourceManager.GetString("StartLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press-release with Id = {0} contains date = &apos;{1}&apos; and title = &apos;{2}&apos;.
        /// </summary>
        internal static string TitleOfPressReleaseIsNotNull {
            get {
                return ResourceManager.GetString("TitleOfPressReleaseIsNotNull", resourceCulture);
            }
        }
    }
}
